### ISSUE TITLE
Need full stack trace in formatters

### ISSUE THREAD

**Issue by sfatula** [Seldaek/monolog#1006]
Some formatters, for example LineFormatter, use getTraceAsString in order to obtain and log the stack trace. This might be ok, except, php tends to truncate the stack trace. An example discussion and solution is here on [stackoverflow](https://stackoverflow.com/questions/1949345/how-can-i-get-the-full-string-of-php-s-gettraceasstring)

This is bad for debugging purposes! Often key things show up with ... instead of a real trace. Can monolog be enhanced to actually report a full stack trace without truncated entries?

**Comment by Seldaek** [comment]
To be honest, monolog isn't a fully fledged debugger.. We have to keep stack traces to a sane level because if we include everything log files get gigantic, logging becomes slow, and some stuff even fails to be logged because of some weird argument appears in the trace that can't be handled and everything falls apart.. We already had enough issues like these in the past, I'd rather keep it sane. In my experience the traces you get are more than enough to pinpoint where the issue more or less came from and then if it's not clear enough run a more in depth debugging session locally.
