### ISSUE TITLE
Can i use mysql to log monolog messages

### ISSUE THREAD

**Issue by ghost** [Seldaek/monolog#102]
Is there any way that i can use Monolog to send log messages to mysql database for reporting purposes.
I wantt o see whats happening on my site

**Comment by waza-ari** [comment]
I know this issue is quite old, however it is listed quite on top of Google searches when looking for a MySQL handler for Monolog. I have implemented such a handler, it is available under the MIT license at GitHub (https://github.com/waza-ari/monolog-mysql) or through Composer (https://packagist.org/packages/wazaari/monolog-mysql).

**Comment by deondazy** [comment]
Thank You @waza-ari
