### ISSUE TITLE
Flushing buffers on request

### ISSUE THREAD

**Issue by vmattila** [Seldaek/monolog#104]
I am looking for options to force all buffering handlers to write their buffers manually. What would be the best method to accomplish that?

The use case for my request is a long running background worker. Due the current BufferHandler implementation, all buffers are written when the script ends. I have a SwiftMailerHandler to alert by email when something erroneous happens, but in the current setup, the emails never arrive (before the worker is closed).

Any comments?

**Comment by benjamindulau** [comment]
@Seldaek setting `stopBuffering` to either `true` or `false` does not seem to have an effect when having a long-running process. We use Rollbar for logging and when running queue consumers (infinite loop) we absolutely need to get errors on Rollbar as soon as they occur. I just can't make it work like I want. Errors are sent when I end the scripts.

Do you have any recommandation?

**Comment by benjamindulau** [comment]
With some more digging I found out that because of the way it is implemented their is no way to properly force a close(). (due to `register_shutdown_function(array($this, 'close'));`)

We could have an option on buffered handlers so they always close() the wrapped handler every time they activate, but I'm not sure you'd want something like that.

For now, I manually invoke close on the RollbarHandler at every loop iteration.
