### ISSUE TITLE
Slack Emoji are displayed on log message

### ISSUE THREAD

**Issue by soullivaneuh** [Seldaek/monolog#1125]
Sample:

![image](https://user-images.githubusercontent.com/1698357/37275687-32d6822a-25e0-11e8-9b57-d835ac64a831.png)

IMHO, it make no sense to activate emojis for log messages.

It should be escaped on the message. Maybe on option exist on the Slack API to disable it.

**Comment by mintobit** [comment]
@Soullivaneuh thanks for reporting this. Since we have multiple Slack Handlers, which one do you use?

**Comment by Seldaek** [comment]
Would https://github.com/Seldaek/monolog/pull/1076/files help for this? I am not sure if emoji support is linked to markdown or not.

**Comment by mintobit** [comment]
Did not find any options to disable emoji in Slack API docs. Wrapping a message into backticks would work (`:package:`), but then it's all highlighted in red, which is kinda ugly. Also, I did not find escape symbols or anything like that so that we can parse message and escape emoji before sending. Any ideas?

**Comment by Seldaek** [comment]
Nope sorry, no idea here..

**Comment by mintobit** [comment]
God bless [stackexchange](https://webapps.stackexchange.com/a/102398).

Here's a way to do it:
```
$slackHandler = new SlackHandler(
    'fake_token',
    '#fake_channel'
);

$logger = new Logger('testlogger', [$slackHandler]);
$softHyphen = "\xC2\xAD";
$logger->log(Logger::CRITICAL, sprintf('Hello world :%1$spackage%1$s:', $softHyphen));
```
