### ISSUE TITLE
Logger::__construct not consistent with Logger::setHandlers

### ISSUE THREAD

**Issue by CC007** [Seldaek/monolog#1131]
When passing a handler array, there is a difference when this is done between passing the array to the constructor of `Logger`, compared to passing it to `setHandlers`. The constructor does support having a `null` value in the array, but `setHandlers` does not, due to the way that the parameters of `pushHandler` are typed.

**Comment by Seldaek** [comment]
The constructor doesn't really support that. The only reason it works as far as I can tell is that the while loop in addRecord will abort whenever it finds a null handler instead of crashing hard, but this is accidental really. I'd rather not allow this, use a NullHandler if you must, but passing null values is a bad idea.

**Comment by CC007** [comment]
Can you then change the constructor so that null is explicitly not allowed? Maybe in your next release only as deprecation warning for those that actually use null.
