### ISSUE TITLE
Compress older log files when rotating

### ISSUE THREAD

**Issue by MikeLund** [Seldaek/monolog#1202]
I think it'd be a good idea for older log files to be gzipped when being rotated, à la logrotate's `compress` directive. For people that store a lot of data in the log files (and/or have a large number of history days), the uncompressed space can really add up.

Performance-wise, even with gzcompress's default compression (6), it goes very quick and saves a ton of disk space.

Useful idea? Thanks!

**Comment by Seldaek** [comment]
IMO if you want fancy features you should use logrotate. It's the right tool for the job really. The RotatingFileHandler is kind of a basic service for when you need something simple.

**Comment by AdamReece-WebBox** [comment]
I would suggest this is a useful feature to have within Monolog because `logrotate` isn't always available. For example in shared hosting environments where we cannot add a `logrotate` configuration, and non-Linux environments where `logrotate` isn't a thing. -- These factors are not always in the developer's control due to client constraints on hosting options, so there is definitely value in having this available from Monolog.

Obviously I can write an external script to do log rotation and compression though this is platform specific. An external script would also have to manage the retention days and purging of expired logs as Monolog would not take into account the different file extensions of a compressed log.

Having this in Monolog would be a good cross-platform solution, particularly as PHP offers a [range of compression options](https://www.php.net/manual/en/refs.compression.php) some of which as standard.

**Comment by Seldaek** [comment]
I agree it might be good to have this available, but it's not a problem I want to tackle nor have to maintain. Feel free to make it available as a package that people can install which can extend/wrap the monolog's core handler functionality.
