### ISSUE TITLE
Monolog and Raven/Sentry or Loggly

### ISSUE THREAD

**Issue by dinbrca** [Seldaek/monolog#1212]
Hi,

I have been using for long time and now I want to add Raven/Sentry for exceptions and Loggly for general logging.
I have added everything and everything is logging correctly.
The only problem I have is that sending a log to a 3rd party is taking time (probably due to the cURL request time taking and stuff).

Some code:
```php
$time_start = microtime(true);

$appContainer->getLogger()->notice("message".rand(1,100000)."{userId}", ['userId' => "asdasd"]);
$time_end = microtime(true);

//dividing with 60 will give the execution time in minutes otherwise seconds
$execution_time = ($time_end - $time_start);

//execution time of the script
var_dump($execution_time);
```
Output is:
```
float(2.7244999408722)
```

For me it seems obvious what is the reason.
Although I would like to know if anyone else experience problems with it because if I add these handlers to my monolog - any request that will send to these will slow down by 2.7 seconds which is enormous.

Thanks for the help.

**Comment by Seldaek** [comment]
If you are going to send all logs and not just errors to some remote log, you got two options IMO:

- Make sure it's a platform that uses UDP and not HTTP to post the data, so that it doesn't block the app
- Use a log file or rsyslog or something to buffer the data locally quickly and then configure your server so that this local file gets streamed off-band to whichever log platform you're using. This is usually possible, if not I'd recommend you switch platforms, there are enough options.

**Comment by dinbrca** [comment]
Thanks.. I already read a bit and decided to use loggly and their rsyslog implementation
