### ISSUE TITLE
Possible regression in 1.24.0 release

### ISSUE THREAD

**Issue by tractorcow** [Seldaek/monolog#1216]
In subclases of RavenHandler you could have a `private $logLevels` method in order to replicate the value in the parent class. As this is now protected, those subclasses will now all cause PHP errors on upgrade to 1.24.0.

An example of the error is:

> Fatal error: Access level to PhpTek\Sentry\Monolog\Handler\SentryRavenHandler::$logLevels must be protected (as in class Monolog\Handler\RavenHandler) or weaker in /Users/damian.mooyman/Sites/testsite/vendor/phptek/sentry/src/Handler/SentryRavenHandler.php on line 23

You can fix this in the subclass by removing the private variable, but I just thought I'd ping back that this upgrade has a tiny risk of breakage.

See https://github.com/phptek/silverstripe-sentry/pull/18 for reference.

I'm not sure if monolog is following semver. Apologies in advance if this isn't a valid bug, but I thought it would be better to provide feedback than not. :)

**Comment by Seldaek** [comment]
That's "funny" because the change was done to facilitate extending the class, and it causes problems with someone extending the class..

We do follow semver, but to be honest at this point we can't possibly do any code change if we want to be 100% BC.

Sounds good that you have a fix going, I'd say move on with it and let's put this behind..
