### ISSUE TITLE
Monolog ^1.0 to ~1.0

### ISSUE THREAD

**Issue by kenjiuno** [Seldaek/monolog#1325]
README.md suggests trying `^1.0` for php >=5.3.0.
However it always installs `1.0`.

So `~1.0` will be better for installation latest version like 1.24.0.

**Comment by Seldaek** [comment]
I believe the issue is you ran the `composer require` command without proper quoting in a windows terminal, which uses ^ as escape character, so it gets removed and you end up requiring version 1.0 without any operator.

`^1.0` is the correct constraint to use however, even tho it's in this case equivalent to `~1.0`

**Comment by kenjiuno** [comment]
Thanks for advice,
I have confirmed that this was my mistake as you have pointed!

This installed 1.0
```
composer require monolog/monolog:^1.0
```

This installed latest one (1.24.0)!
```
composer require "monolog/monolog:^1.0"
```
