### ISSUE TITLE
New Sentry handler

### ISSUE THREAD

**Issue by jlemesh** [Seldaek/monolog#1331]
Package [raven/raven](https://packagist.org/packages/raven/raven) is deprecated, it is suggested to use [sentry/sentry](https://packagist.org/packages/sentry/sentry) ([docs](https://docs.sentry.io/clients/php/integrations/)). Maybe it's a good idea to create new Sentry handler?

**Comment by hkdobrev** [comment]
See #1273. The handler is now ready and released inside the Sentry PHP SDK 2.1.0: https://github.com/getsentry/sentry-php/pull/808

Here's how to use it: https://docs.sentry.io/clients/php/integrations/#monolog

**Comment by jlemesh** [comment]
Thanks for the link!

P. S. The docs are for raven.

**Comment by hkdobrev** [comment]
Hmm, right. It seems they still don't have docs for the new Monolog handler in the docs of the new Sentry PHP SDK. This handler has been released in a stable release less than a month ago: https://github.com/getsentry/sentry-php/releases/tag/2.1.0

You could probably an issue with Sentry to document it.

I think the Monolog docs could also link to the new Sentry handler instead of just providing the old one and leaving users clueless.
