### ISSUE TITLE
AbstractHandler::getLevel() is not part of an interface?

### ISSUE THREAD

**Issue by holtkamp** [Seldaek/monolog#1418]
Monolog version 2

When upgrading to version 2 I encountered something when changing the typehints from `AbstractHandler` to `HandlerInterface`: 

```
Call to undefined method Monolog\Handler\WhatFailureGroupHandler::getLevel()
```

It seems `getLevel()` is not part of an interface, is this correct?

This occured when wrapping a `HandlerInterface` in a `BufferHandler` with a non-default / specific limit

```php
private function bufferHandler(HandlerInterface $handler): void {
  $this->addHandler(
    new BufferHandler(
      $handler, 
      100, 
      $handler->getLevel() //getLevel() might not be defined... for example for a GroupHandler
    )
  );
}
```

Now I circumvented it by detecting an `AbstractHandler`: 

```php
private function bufferHandler(HandlerInterface $handler): void {
  $this->addHandler(
    new BufferHandler(
      $handler, 
      100, 
      $handler instanceof AbstractHandler ? $handler->getLevel() : null
    )
  );
}
```

But this made me wonder: is it on purpose that the `getLevel()` is not part of an interface?

**Comment by stof** [comment]
Yes it is on purpose, because it makes no sense to have it in the interface. `getLevel` in AbstractHandler is the minimum logging level of that handler. But not all handlers have such filtering feature (GroupHandler is purely about logging in all handlers of the group, not about adding additional filtering).
I'm not even sure I would expose that getter at all if monolog was written today, as that's an internal configuration of the handler, not something meant to be used externally.

**Comment by holtkamp** [comment]
Thanks for the swift explanation. I guess my approach of using a `BufferHandler` for a `GroupHandler` makes little sense in this case. But since the function is generic and "allows all `HandlerInterface` instances it seems this additional check for the `$handler instanceof AbstractHandler` is required.

I now start wondering how come this error was never generated when using Monolog 1.x...

Closing this issue now, but feel free to reopen when more discussion is needed / appropriate 🤓
