### ISSUE TITLE
Composer 1.10 invalid PSR-4 autoloaded class

### ISSUE THREAD

**Issue by michaljusiega** [Seldaek/monolog#1437]
Monolog version 2 (probably v1 too).

`Deprecation Notice: Class Monolog\Handler\ElasticsearchHandler located in ./vendor/monolog/monolog/src/Monolog/Handler/ElasticSearchHandler.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185`

There is a class naming error. 
Class name: `ElasticsearchHandler`
File name: `ElasticSearchHandler.php`

**Comment by michaljusiega** [comment]
The ground is a quick reaction: P

**Comment by Seldaek** [comment]
I'm wondering how you got this file with the wrong case, as in git it seems to be called correctly https://github.com/Seldaek/monolog/blob/2.0.0/src/Monolog/Handler/ElasticsearchHandler.php

**Comment by Seldaek** [comment]
In 1.x it used to be called ElasticSearchHandler.php, but was renamed in 2.0, so I am wondering if maybe you installed the package as a git clone it might have failed to rename the file's case correctly when updating from 1 to 2? Otherwise I can not imagine what caused this. In any case I can not reproduce.. Maybe try `rm -rf vendor/monolog/monolog && composer install` ?

**Comment by michaljusiega** [comment]
I think the problem is on the git. For vcs, changing the case in the middle of a sentence has some hidden meaning.

However it works, although I had to first:

```
1. rm -rf vendor/monolog/monolog
2. commit
3. composer install
4. commit
```

then the result is:
![Przechwytywanie](https://user-images.githubusercontent.com/16488888/81590779-a7b44c80-93bb-11ea-8fe3-3a0004eb89b8.PNG)

So we can close. ;)
Thanks for help.
