### ISSUE TITLE
DeduplicationHandler memory leak

### ISSUE THREAD

**Issue by vudaltsov** [Seldaek/monolog#1449]
Monolog version 2.0.2

DeduplicationHandler extends BufferHandler and removes the possibility to override the `$bufferLimit` constructor argument hardcoding it to `0`. This leads to uncontrollable buffer growth in workers.

https://github.com/Seldaek/monolog/blob/bec314a9c14ce8a40650cf13923f5941ef1bfe0a/src/Monolog/Handler/DeduplicationHandler.php#L67

**Comment by Seldaek** [comment]
For workers, you should really make sure you call $logger->reset() in between every job processed, to make sure you only get logs for one job if anything goes wrong, otherwise you are guaranteed to leak memory in some way, or end up logging 1000 jobs worth of random stuff when the 1001th job logs an error.
