### ISSUE TITLE
Problem with encoding on new version

### ISSUE THREAD

**Issue by gmponos** [Seldaek/monolog#1474]
Monolog version 2

Hi.. is it possible you could have a look at this failing build:
https://travis-ci.com/github/gmponos/monolog-slack/jobs/348715512

it uses 2.1.0

while a previous build using 2.0.2 is successful

https://travis-ci.com/github/gmponos/monolog-slack/jobs/335731750#L262

**Comment by gmponos** [comment]
btw the problem is with the custom jsonEncode function (inside monolog) but I can't really understand what change caused this and if it is indeed a problem at my end or monolog.

**Comment by gmponos** [comment]
So I add this test on [UtilsTest](https://github.com/Seldaek/monolog/blob/master/tests/Monolog/UtilsTest.php)

![image](https://user-images.githubusercontent.com/5675248/84577315-fc385680-adc3-11ea-834e-5825651b6b69.png)

I can submit the test with a PR but it will only be a test.. I don't know what's the solution to that.

**Comment by Seldaek** [comment]
This is due to `Added JSON_INVALID_UTF8_SUBSTITUTE to default json flags, so that invalid UTF8 characters now get converted to � instead of being converted from ISO-8859-15 to UTF8 as it was before, which was hardly a comprehensive solution` in 2.1.0.

So we had a half assed solution before which maybe helped your limited test case, and now it breaks. 

You can call `$formatter->removeJsonEncodeOption(JSON_INVALID_UTF8_SUBSTITUTE)` if you want to skip this behavior, but I don't think it's a good idea.
