### ISSUE TITLE
Split chunky log records

### ISSUE THREAD

**Issue by mrtus** [Seldaek/monolog#1513]
Monolog version 2

Currently, we are having some issues where some log records (let's say 1 in 10K records) are not processed correctly by tools because they exceed 8K bytes and the CLI automatically splits everything into a newline after that. This causes log records formatted to json to be invalid since the json is not closed properly.

My question would be, how does one handle such issues, do we need to split our log records into a sizeable chunk or is there a way configure stdout to allow a bigger buffer?

If the solution would be to split these up, could one be pointed towards the right direction to which components to use/adapt?

**Comment by Seldaek** [comment]
I know we've had to make sure we trim logs in some cases to avoid issues when sending them via email as there are some size limits there.

I don't know if there is a way to do this in a generic way because the way you trim and what to trim is very app-dependent.

You could make a custom JsonFormatter which checks the output length and trims it off, closing any open string/object, or you may look at the context data or message length and make sure there isn't too much in there.  If it's due to stack traces you could override normalizeException and make sure you only keep the first few frames and drop the rest if it gets too deep? Just a few pointers.
