### ISSUE TITLE
PHP Fatal error:  Uncaught ErrorException: stream_set_chunk_size()

### ISSUE THREAD

**Issue by otzy** [Seldaek/monolog#1592]
Monolog version 2.3.4

Somehow StreamHandler->streamChunkSize becomes too big:
```
PHP Fatal error:  Uncaught ErrorException: stream_set_chunk_size(): The chunk size cannot be larger than 2147483647 in vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:144
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'stream_set_chun...', '/var/releases/v...', 144, Array)
#1 vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(144): stream_set_chunk_size(Resource id #641, 5583457484)
#2 vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(125): Monolog\Handler\StreamHandler->write(Array)
#3 vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\Handler\RotatingFileHandler->write(Array)
#4 vendor/monolog/monolog/src/Monolog/Logger.php(327): Monolog\Handler\AbstractProce in vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 144

```
probably something is wrong with memory limit calculation.
and the constant MAX_CHUNK_SIZE is not actually used to limit the chunk size

**Comment by RoobieBoobieee** [comment]
We're having the same problem. Our hosting provider sets the `memory_limit` to an unreasonable high amount instead of -1. Which causes this error.

**Comment by degecko** [comment]
`self::MAX_CHUNK_SIZE` is actually correctly calculated but is not used in that function. Instead, the value from this line is used: https://github.com/Seldaek/monolog/commit/70fe0928675d1f1080a9d6496f549baf5ae482a9#diff-a1ddc5c4ead6773b8670f9be5007cbe0239638aedbcf12166acf075a9b8742a2R59

Which has been added a few days ago, and which calculates 10% of the value from `memory_limit`.

On my local setup I have 30 GB of memory limit, which is half my RAM, and it was trying to allocated 3 of that via stream_set_chunk_size(), which has a limit of 2 GB, apparently (the limit matches self::MAX_CHUNK_SIZE).

I think @Seldaek wanted to use `min()` on that line instead of `max()`. :)

For those needing a quick fix, you should set `memory_limit` to a maximum of 20 GB until this is resolved.

**Comment by PandyLegend** [comment]
I also encountered this issue. Setting the `memory_limit` to 20GB didn't work though, I had to set it to 18GB. Hopefully the issue will be resolved shortly.

**Comment by Seldaek** [comment]
Sorry about the trouble here.. I didn't realize the previous max constant was a hard limit, and definitely did not assume people would have memory limit set to 30GB :) Will get a release out shortly.
