### ISSUE TITLE
Undefined property $maxDepth JsonFormatter 

### ISSUE THREAD

**Issue by omadihyphen** [Seldaek/monolog#1643]
Monolog version 1

Getting this error when try to use Json Formatter
```
ErrorException: Undefined property: Monolog\Formatter\JsonFormatter::$maxDepth in /var/www/html/vendor/monolog/monolog/src/Monolog/Formatter/JsonFormatter.php:147
```

it's happen after this changes release https://github.com/Seldaek/monolog/pull/1633

**Comment by Seldaek** [comment]
It is weird because the maxDepth property exists in https://github.com/Seldaek/monolog/blob/1.x/src/Monolog/Formatter/NormalizerFormatter.php#L27 which is the parent class to JsonFormatter. Do you see something else in your vendor dir? Do you perhaps have multiple monolog versions or multiple vendor dirs running concurrently on the same project?

**Comment by omadihyphen** [comment]
I am checking the whole project folder and seems like we only use this `"monolog/monolog": "~1.11"`
but yeah it's weird because just noticed this error only happen in the docker container but looks fine with using XAMPP

The App is using `php 7.2.3` and `Laravel 5.2`
