### ISSUE TITLE
Better library support/use cases

### ISSUE THREAD

**Issue by zampettim** [Seldaek/monolog#255]
One big issue is that Monolog doesn't really support being used as the logging implementation for libraries and other code that is intended to be primarily used in other applications. 
Basically, I should be able to instantiate a Logger instance with just a name (which I understand is technically allowed now), and then at runtime, have a way to specify the handlers and processors that should be applied to that channel, ideally through configuration via a file or API. This is similar to how other logging implementations work, and provides for a high degree of flexibility.

**Comment by rantonmattei** [comment]
Just came across this issue. It's been a problem for us at [The Orchard](http://www.theorchard.com/) since we are big Monolog users. I've worked on a project called [monolog-cascade](https://github.com/theorchard/monolog-cascade). It is open source as well. This should solve most of your issues. You can configure a bunch of loggers and handlers using a single config file (Yaml or JSON).
First version got ou a few days ago. Try it out and let me know what you think. And feel free to contribute if you like it!
Thanks

**Comment by keywan-ghadami-oxid** [comment]
@rantonmattei i had the same issue but was not aware of your solution so i did nearly the same thing https://github.com/keywan-ghadami-oxid/monolog-configuration. Looking forward to compare implementations.
