### ISSUE TITLE
occur 'Array to string conversion Exception' when I use NormalizerFormatter in monolog

### ISSUE THREAD

**Issue by GNUSource** [Seldaek/monolog#562]
Here is code, does it has wrong?

        $separator = ('Linux' === PHP_OS) ? '/' : '\\';
        $fileName = storage_path()  . $separator . 'logs' . $separator . 'notificationLogs' . $separator . 'notification.log';
        $formatter = new NormalizerFormatter('Y-m-d');
        $handler = new RotatingFileHandler($fileName, 20, Logger::INFO);
        $handler->setFormatter($formatter);
        $log = new Logger($fileName);
        $log->pushHandler($handler);
        $log->addWarning('Foo', ['a' => 'test']);
        $log->addError('Bar', ['b' => 'test']);

**Comment by Seldaek** [comment]
The problem is you use a normalizer formatter which only normalizes the data but does not stringify it, and the rotating file handler will write log records as strings to the file so you should really use it with a LineFormatter (which extends from Normalizer anyway)

And BTW instead of $separator you can just use `/` everywhere, this works fine on windows too.

**Comment by GNUSource** [comment]
i know, think you!
