### ISSUE TITLE
LogstashFormatter and WebProcessor issue

### ISSUE THREAD

**Issue by d3sire** [Seldaek/monolog#610]
This issue appears when using formatter and processor mentioned in the title. URL information from extra of webprocessor is copied to the source path of logstashformatter which increases size of log with unnecessary information.
Edit: temporary solution for me was to comment source_path and server section in a LogstashFormatter source code.

**Comment by Seldaek** [comment]
I think it's good to move it to source_path as that seems a more appropriate/specific location in logstash, but probably it should be removed from the extra key then when we do that (same for extra.server that goes in source_host). What do you think about that? I would delay this until 2.0 though because it's a bit of a BC break..

**Comment by Seldaek** [comment]
Closing as Logstash V0 is not supported in monolog 2.x anymore.
