### ISSUE TITLE
PsrLogMessageProcessor should be a Formatter instead

### ISSUE THREAD

**Issue by KevinMGranger** [Seldaek/monolog#612]
From the docs on Processors:
>The second way is to add extra data for all records by using a processor. Processors can be any callable. They will get the record as parameter and must return it after having eventually changed the extra part of it.

Currently, the PsrLogMessageProcessor is the only Processor that modifies the message itself instead of the `$record['extra']` property.

If we look at the PSR-3 standard:
>Implementors MAY use placeholders to implement various escaping strategies and *translate logs for display.*

(emphasis mine).
Replacing PSR-3 placeholders is a formatting operation, and thus should be done as a Formatter.

I understand why it might be appealing to have it as a Processor -- this way, it is Handler agnostic and is run before it hits any Formatters. Perhaps it could wrap any existing Formatter, and do the replacement before it is formatted by the wrapped one?

This would likely need to be a backwards-incompatible change. Perhaps it could be changed for the 2.0 release?

**Comment by Seldaek** [comment]
If then yes it would be in 2.0. The question is does it really make sense or not. As it is, it doesn't do any translation, it only replaces placeholders from context/extra into the message. If you want a complex implementation doing translation and so on, you can do that at the formatter level if that makes more sense.

I think the way this simple implementation works, processor is easier because it can be added before the formatter on a per-handler basis. It's simple for users and it just works, so what's the big deal if it's not purely adhering to the definition of a processor?

**Comment by KevinMGranger** [comment]
To be honest, I can't remember why I wanted it changed. I could have sworn I had a good reason!

I'll close this for now and get back to you if I can remember.
