### ISSUE TITLE
Monolog Truck Factor

### ISSUE THREAD

**Issue by gavelino** [Seldaek/monolog#626]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Monolog** and obtained a value of **11**.

The developers responsible for this TF are:

Jordi Boggiano - author of 64% of the files
Christophe Coevoet - author of 9% of the files
Marc Abramowitz - author of 3% of the files
Hennadiy Verkh - author of 3% of the files
adlawson - author of 3% of the files
Markus Bachmann - author of 3% of the files
skymeyer - author of 3% of the files
Eric Clemmons - author of 3% of the files
Dominik Liebler - author of 3% of the files
Jesper Skovgaard Nielsen - author of 3% of the files
Gyula Sallai - author of 2% of the files

To validate our results, we would like to ask **Monolog** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Monolog**?

(b) Do you agree that **Monolog** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Monolog** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by Seldaek** [comment]
a) Yes and no, a lot of those listed are one-shot contributions because authorship of a file doesn't really indicate much in the context of monolog which is made out of many adapter classes for various logging services/targets. So the TF is probably lower than 11.
b) On the other hand, it's a fairly simple and stable project, and disappearance of all or most of those 11 would probably not lead to a disaster. Someone could easily take over I think.
c) see b, simplicity/minimalism make it easy to pick up I think.
