### ISSUE TITLE
Syslog has UDP but not TCP support

### ISSUE THREAD

**Issue by derekchan** [Seldaek/monolog#627]
There is a SyslogUdpHandler, but no TCP implementation. Is there some special reason for this?

I can take a stab at implementing it, if the reason is only because nobody has ever requested.

**Comment by staabm** [comment]
@derekchan why do you need TCP instead of UDP? Any problem with the UDP handler?

I don't think there would be a problem to have a tcp handler, but I guess there is not reason to have one :).

**Comment by Seldaek** [comment]
Logging via TCP is not really a great idea IMO because you slow down the app with network delays quite a bit just to guarantee log delivery which is usually not critical. If log delivery is critical I think dumping to disk or redis and then having another process streaming the data via TCP to the log server is a lot more efficient.

**Comment by cdmckay** [comment]
The problem with UDP syslog is that the log messages can come in out of order, especially if they're sent very close together.

**Comment by Seldaek** [comment]
Yes, that's true, but then again there are many ways to reliably ship logs off a system, using TCP in the logger is not one of the good ones IMO.
