### ISSUE TITLE
SlackHandler fails with too long messages

### ISSUE THREAD

**Issue by PhilReinking** [Seldaek/monolog#664]
I'm trying to log my Application Exceptions through SlackHandler, but they are not showing up. I found out that the messages are too long for the Slack Webapi.

When I try the [Slack Api Tester](https://api.slack.com/methods/chat.postMessage/test) I get the following error:

    Request-URI Too Long
    The requested URL's length exceeds the capacity limit for this server.

As a quick workaround I used the substr function to limit the Exception message to 300 characters.

```php
$record['message'] = substr($record['message'], 0, 300) . '...';
```

**Comment by JustinHook** [comment]
@PhilReinking I'm unable to recreate this issue. The Slack API tester calls `chat.postMessage` via `GET` which is why I think you are getting `Request-URI Too Long`.

Monolog calls `chat.postMessage` via `POST` and I've been able to send a message with a length of ~45kb without any issue. How large are your exception messages? What response do you get back from Slack?

**Comment by PhilReinking** [comment]
Ok, I think the problem was due to an incorrect configuration. The Handler used the Test API Token, which you can generate as an developer on Slack documentation pages. Maybe this developer key has some restrictions, which the normal Integration API keys do not have.

I configured it now to use the correct API key from the Bot Integration Page and it seems to work now.
