### ISSUE TITLE
Fatal errors have no backtrace, IntrospectionProcessor can be smarter

### ISSUE THREAD

**Issue by razvanphp** [Seldaek/monolog#693]
I can provide more info on this, but according to our debugging, when a fatal error occurs, the line, function and co are in the `context` not in the `extra`, so `IntrospectionProcessor` does nothing, and puts null in all fields.

I think one of them should be smarter. I can prepare a PR if needed.

**Comment by patrick-mcdougle** [comment]
:+1: The fatal error handler passes in all the data (message, type, line no) from the exception except for the trace, I think it should just pass the exception itself in and let the formatters decide what should be included from the exception object. For example, the line formatter could decide if it should include the trace or not.

**Comment by Seldaek** [comment]
I think this can be fixed in 2.0 as php7 throws exceptions for fatal errors. But in 1.0 I don't see how we can fix anything if it really doesn't work right now.

**Comment by Seldaek** [comment]
Closing as 2.0 now should handle fatals as exceptions, at least most. For the others like out of memory error I am not sure what we can do to be honest. If you find that it's still lacking and find a way to improve it please send a PR :)

**Comment by tractorcow** [comment]
@Seldaek sorry to open an old issue, but in SilverStripe 3.x (before we moved to monolog) we would capture the stacktrace with `debug_backtrace()` in our error handlers.

https://github.com/silverstripe/silverstripe-framework/blob/abe0e961927880021d59a8f0bdd475dbfe0f7570/dev/Debug.php#L572-L575

(this is super old code, so don't judge us too harshly for the bad style)

Although you cannot capture this from error_get_last(), you can create a separate registrar on ErrorHandler for the last stacktrace from this error. We could assign this in `ErrorHandler::handleError`, and `ErrorHandler::handleFatalError` could inspect this, passing it into the logger. :)

Pseudocode follows (because I'm lazy)

```php
handleError() {
	$trace = debug_backtrace();
	if (!$fatal) {
		$logger->log($lastError, array('code' => $lastError['code'], 'trace' => $trace));
	} else {
		$this->fatalErrorTrace = $trace;
	}	
}
handleFatalError() {
	$lastError = error_get_last();
	if ($fatal) {
		$lastTrace = $this->fatalErrorTrace;
		$logger->log($lastError, array('code' => $lastError['code'], 'trace' => $lastTrace));
	}
}
```

If you think this is an appropriate approach is it worth my submitting a pull request as a proof of concept?

**Comment by tractorcow** [comment]
Given the work required was no larger than my "lazy" pseudocode I've gone ahead and done so anyway. :)

https://github.com/Seldaek/monolog/pull/1080

Please let me know if I am going in the right direction.
