### ISSUE TITLE
Create new GitHub Issues automatically

### ISSUE THREAD

**Issue by DavidGarciaCat** [Seldaek/monolog#697]
Hello,

I've been using Monolog with Symfony, and I think this is an interesting tool, specially because can send an email with the error that we are logging.

However, I think that can be an interesting update if we can provide to Monolog with the expected config in order to allow the library to create new GitHub Issues automatically when (just an example) we receive a `CRITICAL` error.

I don't know if you are agree with me, but I think it can be useful on some kind of projects.

Cheers,

**Comment by robbieaverill** [comment]
Thoughts on this - what if the same critical error is produced repeatedly for the same reason? Do you end up with *n* number of duplicate GitHub issues?

**Comment by DavidGarciaCat** [comment]
@robbieaverill :+1: You're right. Then my question is: if we are receiving the same error all the time, we should fix that error ASAP, right? And if we are sending emails, we are receiving the same error all the time, so the result is the same, but if we can create the GitHub issue automatically is more easy to handle when we work with some teammates.

**Comment by djallits** [comment]
Agree w/ @robbieaverill here. For instance I run a legacy PHP application that runs a process every 5 minutes as a scheduled task. It essentially batches orders from a variety of front-end clients. It is not unusual for me to receive upwards of 200 emails about an issue. Yes, this is due to poor code. However, I would not want to spend my valuable time, nor anyone else's, closing 200 GH issues for the same LogLevel 500+ issue.

I believe this is why we pay for 3rd party monitoring and alerting (i.e. New Relic, PagerDuty, etc.).

**Comment by quantumpacket** [comment]
I concur with the above statements it would fill up very quickly with dupes. Maybe have the email messages or whatever make a link to `https://github.com/vendor/repo-name/issues/new`? That's at least one less step needed to open a Github issue.

**Comment by DavidGarciaCat** [comment]
:+1: Closing this issue then, Cheers
