### ISSUE TITLE
2.0 refactoring: use the decorator pattern

### ISSUE THREAD

**Issue by mnapoli** [Seldaek/monolog#705]
Hi! I'm bouncing on [this](http://seld.be/notes/the-road-to-monolog-2-0 said):

> If you use Monolog a lot and have thoughts on what should change in the design, please open an issue!

Here is something I've had on my mind for some time. Monolog's internal is complex:

- we have handlers, formatters and processors: generic names, similar concepts (especially the last two) makes writing custom ones not easy and confusing
- a log message is an array which is not really nice to use (see #516)

I'm opening this issue to discuss a possible idea for a refactoring: have a single concept of "handler" (or could also be named "logger"), and represent the message as an object. Additionally, instead of having to use one big "glue" classe (`Monolog\Logger`) everything could be assembled using **the decorator pattern**.

Here is a very simple example:

```php
class StdOutLogger implements Handler
{
    public function handle(Log $log)
    {
        echo $log->getMessage();
    }
}
```

Notice this doesn't care about formatting, log level, etc etc. The implementation is dead stupid. If we want to format the message, we can decorate the logger with a formatter:

```php
class LogFormatter implements Handler
{
    private $next;

    public function __construct(Handler $next)
    {
        $this->next = $next;
    }

    public function handle(Log $log)
    {
        $log->setMessage(/* format the message here */)

        // pass to the next handler
        $this->next($log);
    }
}
```

Again, this implementation is dead stupid and only cares about formatting the message. The same could be done to:

- filter logs only for some log levels
- dispatch to multiple sub-handlers (e.g. log to syslog + file + ...)
- "fingers crossed" handler
- ...

Advantages:

- internally, the code is very easy to maintain and clear
- for users, writing new handlers is much easier
- users can create all the behavior they want (handlers can be chained in many ways)

Now there is of course a bit more complexity for the user when assembling all those handlers to create their logger. Illustration of that:

```php
$logger = new LogLevelFilter(
    Logger::INFO,
    new MessageFormatter(
        '{date} - {level} - {message}',
        new SyslogHandler
    )
);
```

That could be managed by a "log builder" (or a factory, or whatever). Here is an example:

```php
$builder = new LoggerBuilder();
$builder->chain(LogLevelFilter::class, Logger::INFO); // log only above INFO
$builder->chain(MessageFormatter::class, '{date} - {level} - {message}');
$builder->chain(SyslogHandler::class);
$logger = $builder->build();
```

Or a specific simple logger could also hide completely all the complexity:

```php
$logger = new SimpleLogger(new SyslogHandler);
$logger->setLogLevel(Logger::INFO);
$logger->setFormat('...');
```

Hell it would even be possible to re-implement the current `Monolog\Logger` class using those new handlers to keep full backward compatibility of the API of this class!

### Variants of the idea

- use `Psr\Log\LoggerInterface` as the interface for handlers, which makes every one of them a valid PSR-3 logger: very simple to use, optimized, etc.

I love that idea as I sometimes wanted to use a very simple logger (e.g. log everything to stdout). Here is an example:

```php
class SomeHandler implements LoggerInterface
{
    use Psr\Log\ LoggerTrait; // to avoid implementing all the methods

    public function log($level, $message, array $context = array())
    {
        // ...
    }
}
```

It's a little more verbose (and we loose the `Log` object), but to me it's PSR-3 at its finest: every single handler can be mixed with any other PSR-3 logger (or handler) out there and Monolog becomes the main repository of PSR-3 implementations. I can't express how much I love this idea.

- handlers could also be straight PHP callables, which is very similar to the middleware pattern: the whole thing could be implemented like PSR-7 middlewares, handlers would be extremely easy to write

Example:

```php
$logLevelFilter = function (Log $log, callable $next) use ($minLevel) {
    if ($log->getLevel() >= $minLevel) {
        $next($log);
    }
};
```

Looks a lot like PSR-7 middlewares! It's very simple to write, and of course `callable` means those can be written as classes using `__invoke()`.

### Conclusion

I know this may look like over-engineering, but on the contrary I would say it's simpler than the current architecture. I would understand however if you disagree with me on this ;)

**Comment by Seldaek** [comment]
That's a lot of text ;) But I'll try to answer..

- Generalizing handlers/processors/formatters into one thing that just converts a message and passes it on.. why not. It scares me a bit in terms of simplicity of configuration though, because right now most handlers have a default formatters and you rarely ever need to actually configure one, if you don't want to dive in too much it's pretty easy and you never even have to know about the formatter concept.

Processors though I agree are a bit of a messy thing.. I just like that they are simple callables vs having to create a generic-handler-thing-implementing PSR-3 to be able to modify/add a field on the log record.

- PSR-3 interface for handlers.. That could work but it'd be a bit wasteful I think as if everything has to accept only a string $message every handler would have to create a timestamp and so on. Also you'd end up logging different actual log records with different timestamps.. Unless we store all the stuff in `$context` but IMO that's an oversimplification that gets a bit messy.

- Having log records as objects vs array.. Why not but I am not entirely sure of the benefits to be honest.

- Handlers as callables.. why not it joins the processor callable idea.

Just raw thoughts, not sure about any of this really, I'd need to think about it some more.

**Comment by stof** [comment]
> Handlers as callables

This would not work for batched handling.

Regarding the usage of decoration to format messages, I don't agree with that. Each handler has a different formatting need depending on what they do with the message, so expecting them to receive a message already formatted in their own way breaks the OOP principles

**Comment by mnapoli** [comment]
If a handler needs specific formatting then of course the handler should format the message itself.

If not (e.g. when writing to a stream), then the responsibility can be offloaded to a separate class.

**Comment by Jean85** [comment]
Question to @mnapoli : the decorator pattern shouldn't prescribe a "wrapping" technique instead of a concatenation? I think this is at the base of the issues raised by @stof

**Comment by mnapoli** [comment]
@Jean85 coud you provide an example maybe? I'm missing your point I think.

**Comment by Jean85** [comment]
I was referencing the classical-gang-of-four definition of the decorator pattern; in this case, the implementation would look like approximately like this:

    class LogFormatter implements LogMessage
    {
        private $message;

        public function __construct(LogMessage $message)
        {
            $this->message = $message;
        }

        public function getMessage()
        {
            $this->decorateMessage($this->message->getMessage());
        }
    }

In this case, the base object/interface is the log message, and the class that decorate it implements the same interface as the message, overwriting what is needed. In this way, the decoration is done via encapsulation.

This implementation shows how (in a OO way) this approach may be limited, but in a good sense: the pattern makes explicit what should and shouldn't be done with a decoration like this.

All this is obviously IMHO :8ball:

**Comment by mnapoli** [comment]
I still don't get the point. I am talking about decorating loggers, you are talking about decorating log message objects: is this intentional? Are you saying the latter is better than the former?

**Comment by Jean85** [comment]
It's partially intentional; I'm not totally privy about Monolog internals, and I'm pretty sure that making messages as object is the best course of action.

I'm not sure about what is better between this two strategies, I was just remarking that IMHO what you're proposing it doesn't seems to me like a decoration, but more like a chain, and that @stof was pointing out  that it does hide some problems of concatenation... All formatting actions can be concatenated? Are we sure?
