### ISSUE TITLE
Line formatter doesn't support `%context.key%`

### ISSUE THREAD

**Issue by joshuaspence** [Seldaek/monolog#717]
It was not immediately obvious to me why `%context.key%` isn't handled by the `Monolog\Formatter\LineFormatter` class whereas `%extra.key%` is. This could just be a documentation issue, but ideally `%context.key%` would just work as expected.

**Comment by Seldaek** [comment]
Yeah that's funny.. it's been like that since day 1 pretty much. https://github.com/Seldaek/monolog/commit/ed6b0e32a262b57ccdacf1145c225350f6e68eb9 I don't think it was really a conscious decision it just grew without it. I'll fix that.

**Comment by Seldaek** [comment]
Fixed in https://github.com/Seldaek/monolog/commit/25131bb5f655f0c71214209c23dd30061e8a10c3

**Comment by nitso** [comment]
I've used context field as a string, so new version breaks my code.

Contract (before fix) declares nothing about type of `context` property. So monolog accepts a string or other scalar value in `context`. 
Such experience can be a wrong practice, but this fix can brake some other project also.

**Comment by stof** [comment]
@nitso the context is typehinted as an array in all methods of the Logger. So I don't see how you could end up with a string

**Comment by Seldaek** [comment]
Indeed that seems like you did something really strange along the way. I don't think it's possible to reach this with only using monolog classes.

**Comment by nitso** [comment]
That's true. I've overrided `LineFormatter::format()` in my formatter to have comma-separated values instead of json in context field:

    public function format(array $record) {
        $record['context'] = join(',', $values);
        return parent::format($record);
    }

In previous version it worked well because every `$record` item except `extra` was directly passed into `stringify` method: https://github.com/Seldaek/monolog/blob/25131bb5f655f0c71214209c23dd30061e8a10c3/src/Monolog/Formatter/LineFormatter.php#L100

I assume that should be done with processor. I'll fix previous version until refactoring. But you may take into consideration that your fix breaks compatibility in some way :)
