### ISSUE TITLE
ReactPHP or similar non-blocking I/O implementation

### ISSUE THREAD

**Issue by aleemb** [Seldaek/monolog#735]
I have been considering logging services including GetSentry and BugSnag. However, I can't come to terms with the default monolog implementation sending synchronous requests. If I am doing offline development, every innocuous error will cause Monolog to timeout while trying to report to the service which can be an annoyance.

Error reporting can be a nasty performance bottleneck, especially if I am dealing with high volume servers where milliseconds matter and the latency of the error reporting server alone can trump the load times of the entire app.

I am unable to justify using this in production out-of-the-box due to these constraints. Any alternative guidance would be helpful.

**Comment by Seldaek** [comment]
There are two ways to do performant logging IMO: 

- Log to filesystem only, and then use something else (logstash, heka, ..) to read the logs and send them off to an aggregation system in the background.
- Log using UDP sockets, so that there is no waiting for ACKs, and no problem if the remote host is down (you're just losing logs, but that's *usually* better than slowing things down, depends on the app requirements).

All log platforms that require you to use TCP/HTTP to send them logs are completely missing the point IMO. They might be acceptable to log errors because those requests are dead in the water anyway and shouldn't occur too often anyway, but if you do logging of events and such, you really want something that performs.

As for ReactPHP/Async, yes we could but that's quite an intrusive requirement and needs tighter integration with the app, so it might be best researched in an external package than in core monolog IMO.

**Comment by Ocramius** [comment]
Was digging around, interested in making local stream-based logging a bit faster: found https://github.com/amphp/log, which matches the OP questions.
