### ISSUE TITLE
DateTime related changes in 2.0

### ISSUE THREAD

**Issue by Seldaek** [Seldaek/monolog#736]
Things to consider:

- Switch to DateTimeImmutable?
- Extend to make datetimes json serializable (#402) and make sure the format is configurable somehow?
- Disable microsecond precision by default for performance?

**Comment by stof** [comment]
> Switch to DateTimeImmutable

:+1: for that

> Disable microsecond precision by default for performance?

This looks like a good idea. People caring about the microsecond precision of their log can enable the feature.
The NormalizerFormatter (and so its child LineFormatter too) drops the microseconds by default when formatting the date anyway due to the default date format. So the performance is degraded for nothing.

> Extend to make datetimes json serializable and make sure the format is configurable somehow?

if the format needs to be configurable, it will be hard to do it using JsonSerializable, as the DateTimeImmutable won't know the configuration of each formatter (and formatters may have different configs)

**Comment by Seldaek** [comment]
Please check out https://github.com/Seldaek/monolog/pull/793 /cc @holtkamp too
