### ISSUE TITLE
Getting token to use Monolog with Slack

### ISSUE THREAD

**Issue by nisbeti** [Seldaek/monolog#743]
It is not straight forward to get a token to use monolog with Slack. The expectation is that you write an OAuth client to get the token, but it is possible to get it manually. These are the steps I followed today:

You should already have an account and a channel set up that you want to send error messages to.
1. Create a new Slack App - https://api.slack.com/applications/new which will give you a client_id and a client_secret which you need for step two. You will need to enter a redirect URI, which can be any page for this purpose.
2. Got to https://slack.com/oauth/authorize?client_id=[client_id]&scope=chat:write:bot
3. Authorise App on the page that is returned.
4. From the URI copy the code that is returned.
5. Go to https://slack.com/api/oauth.access?client_id=[client_id]&client_secret=[client_secret]&code=[code]
6. Your token is in the JSON that is displayed.

TO debug errors insert echo fread($this->resource, 1000); at the end of the writeToSocket method of Monolog/Handler/SocketHandler (see https://github.com/Seldaek/monolog/issues/514)

**Comment by johnhunt** [comment]
This method doesn't work for me, I just get the following json response from oauth.access:

```
{
"ok": false,
"error": "invalid_code"
}
```

Wouldn't it make more sense to just use the incoming webhook functionality? This is far easier to set up than having to do a manual oauth dance..

**Comment by damienalexandre** [comment]
It worked for me. To bad this handler is not using a simple but effective web-hook, it would be much simpler to configure.

**Comment by jsafield** [comment]
omg. 
I don't want to open the page; https://nimbustest.slack.com/oauth/reflow/ and return back after clicking Authorization.
 https://slack.com/oauth/authorize?client_id=[client_id]&scope=chat:write:bot
Is it only way to get code?? How can I get code in the server?

**Comment by Gummibeer** [comment]
I'm working with a test token https://api.slack.com/docs/oauth-test-tokens but a web-hook would be much better and simpler! :)

**Comment by hkdobrev** [comment]
I also think that this is not about documentation. The Slack handler should use incoming webhooks. They are made for things like that and are quite simpler to configure. The Slack OAuth apps get published and you describe how other users could install them. I'm sure almost all cases for the Monolog Slack handler are about logging something to your team Slack.

We could change the way the Slack handler works in a backward-compatible manner as the tokens for webhooks and OAuth apps are structured differently and webhooks also need the team slug. If we don't want to support both cases, then this should be a BC break and it would be great if that could be decided before 2.0 is out so we could get it in that release if needed.

@Seldaek What do you think?

**Comment by Gummibeer** [comment]
@hkdobrev I'm also for a change to webhooks and no longer using oauth tokens.

**Comment by Seldaek** [comment]
Yeah that sounds good I agree.. The current model sounds a bit crazy for what it does. If you can PR a BC-approach to 1.x I'd be all for it.

**Comment by hkdobrev** [comment]
@Seldaek Great! I have some free time between 3rd-6th September so I'll be able to open a PR next week 😺

**Comment by Gummibeer** [comment]
@hkdobrev I can't wait for it - if you need help or any prework just call me.^^

Our current custom SLackHandler depends on the https://github.com/maknz/slack package but it works pretty well:

```php
<?php
namespace App\Libs\Logging;

use Monolog\Handler\AbstractProcessingHandler;
use Monolog\Logger;

class SlackHandler extends AbstractProcessingHandler
{
    public function __construct($level = Logger::WARNING, $bubble = true)
    {
        parent::__construct($level, $bubble);
    }

    protected function write(array $record)
    {
        try {
            \Slack::to(config('slack.channel'))->withIcon(':beetle:')->attach([
                'fallback' => $record['formatted'],
                'color' => 'danger',
                'fields' => [
                    [
                        'title' => 'Server',
                        'value' => array_get($record, 'server', env('APP_ENV', 'cali')),
                        'short' => true
                    ],
                    [
                        'title' => 'Level',
                        'value' => array_get($record, 'level_name', 'WARNING'),
                        'short' => true
                    ],
                    [
                        'title' => 'URL',
                        'value' => array_get($record, 'extra.url'),
                        'short' => true
                    ],
                    [
                        'title' => 'Request-IP',
                        'value' => array_get($record, 'extra.ip'),
                        'short' => true
                    ],
                ],
            ])->send(explode("\n", array_get($record, 'message'))[0]);
        } catch (\Exception $e) {
            // ignore it
        }
    }
}
```

**Comment by hkdobrev** [comment]
@Gummibeer Thanks! I don't think I'd use the slack package you've linked though. I don't think it's a good idea to add a new dependency just for that and from what I see it would only work for incoming webhooks. I'd use the existing Monolog handlers infrastructure for sending to the Slack API or to the webhooks endpoint depending on whether you've passed a team name.

Thanks for the input though! It is indeed helpful and I'll try to add some goodies like better attachment support. I'll try to open a PR early to gather feedback.

BTW is your handler open-source so I could look at it in more context?

**Comment by Gummibeer** [comment]
@hkdobrev It's included in a private project - the context is the laravel framework v5.2 that's why there are some global aliases and functions like `array_get()`. And I know that this one isn't perfect and not made for public usage - it was a quick way cause we already have this slack package for other messages in use.

**Comment by Seldaek** [comment]
Ping everyone here, if you care about easy Slack usage please give https://github.com/Seldaek/monolog/pull/846 a shot and give us feedback over there, that would be much appreciated :)

**Comment by tzookb** [comment]
someone is doing the change to webhooks?
or I could try doing it?

**Comment by hkdobrev** [comment]
@tzookb I've started doing it over at #846. I just have a couple more changes and some tests. I think I'll push it all by the end of the week :)

**Comment by tzookb** [comment]
awesome @hkdobrev ,

well ping us when you done it, I used a quick hack for now 🗡

**Comment by mirfilip** [comment]
Using OAuth is a way to go if you create a Slack app that will later offer the possibility to do some actions **on Slack user behalf**. That's why there is an association with `ClientId` and you generate an OAuth token per user. It makes sense if you plan on offering this app for others to use.

Majority of people using Monolog are not interested in that. Oftentimes, teams just want to add logging to Slack for some project the team maintains. It's not on behalf of any team member. That's what Webhooks are for and as others pointed out, the original `SlackHandler` should have been made that way in the first place.

Sure, if you google "slack monolog integration" you'll find tutorials stating "nah, just create that token and it will work". It will, just think about what happens when the team member that did the integration quits and the user is removed from Slack.

[There is a 3rd party handler that uses Webhooks](https://github.com/Pageon/SlackWebhookMonolog), although I'm not a fan of its "strict OOP" way of configuring it.

BTW. Mentioning that such changes to existing `SlackHandler` would break BC show that handlers for popular services (`HipChat`, `Slack`, `NewRelic`) shouldn't be a core part of this library. Just my opinion.

**Comment by Seldaek** [comment]
Yeah you aren't wrong on that last note @mirfilip - maybe these new handlers should just be published by @hkdobrev and I remove Slack stuff in v2.. For the others unless we have maintainers coming forward it's kinda difficult.

**Comment by hkdobrev** [comment]
@Seldaek, could you elaborate more on what you mean? Remove everything regarding Slack from Monolog itself in v2?

What I get from @mirfilip's argument is that the Slack API handler should be removed, but I don't see why to remove the webhooks and slackbot ones unless all handlers are moved to a separate repo each.

**Comment by Seldaek** [comment]
Well I meant if you are happy to maintain it for example you could publish
it all as one or 3 packages and I remove slack entirely from v2 and
deprecate it in v1 pointing to your repo. Then you can more easily iterate
and break BC etc independently from monologs release cycle.

Let me know :) either that way or I merge and then tag the next 1.x but I
wanna move forward soon with the tag no matter how.

**Comment by mirfilip** [comment]
@hkdobrev @Seldaek yeah, my argument was:
It's cumbersome to keep handlers for 3rd party services with core Monolog, as they are subject to 3rd party APIs and thus can change in time.

What I mean by 3rd party API changes is: today Slack supports three types of interaction: with OAuth token as a Slack User, webhook as anyone, slackbot as artificial bot user. Tomorrow, there can be more ways. It's problematic for Monolog to keep up with these changes and release the new version (possibly with BC breaks) just because something has changed in 3rd party apps/services. That's not a problem with well estabilished handlers like php's `ErrorLogHandler`.

My last suggestion is to keep all related handlers in one repository, e.g. all three ways to log to Slack in one repo.

**Comment by hkdobrev** [comment]
@Seldaek My suggestion would be to release these handlers as implemented in #846 in 1.x.

I'm happy to maintain them as 3rd party packages for Monolog 2.x if you actually decide to split built-in Monolog loggers into separate packages. If I'm releasing a package tied to another library such as Monolog I'd prefer to be based on the new Monolog 2.x from the start.

@mirfilip I personally prefer 3 separate packages - 2 of which (Slack API handler and Slack Webhooks handler) could depend on another common package for formatting using interfaces if Slack continue to support same formatting for different APIs. Users would choose the one they want in a similar way they choose cache provider when using a PSR-6 cache library with different providers for cache implementation.

**Comment by mirfilip** [comment]
@hkdobrev Right. I just suggested the smallest sane fragmentation. What you say seems logic as well.

**Comment by Seldaek** [comment]
Closing as the new Slack handlers are merged. https://github.com/Seldaek/monolog/releases/tag/1.22.0

**Comment by NikolaiAKiselev** [comment]
Bot User OAuth Access Token can be found in App features -> OAuth & Permissions -> OAuth Tokens & Redirect URLs

**Comment by jordanboston** [comment]
Yes @nikkiselev !  

I got the token by following that after setting permissions and installing the app, it shows up here:
![Screen Shot 2019-12-18 at 2 19 26 PM](https://user-images.githubusercontent.com/1487071/71124245-acc0f700-21a1-11ea-905f-c0065b4146e0.png)
