### ISSUE TITLE
WebProcessor POST details

### ISSUE THREAD

**Issue by pittyplatsch** [Seldaek/monolog#748]
Would anyone be interested in having POST (form) details logged by the WebProcessor? I understand it could be too much information or may contain sensitive information, so it definitely should be optional. But in general I would like to have it and wouldn't mind putting a PR together if it would be accepted?

**Comment by Seldaek** [comment]
IMO having this with every log record is a bit overkill.. What I tend to do is send a `->debug("$requestMethod $requestUri", ['post' => $_POST]);` or equivalent so in case of error combined with a FingersCrossedHandler I get the full details of the request.

**Comment by pittyplatsch** [comment]
@Seldaek Thanks for your comment. One could argument that the WebProcessor itself is "a bit overkill", but it's certainly handy and very easy to add to all log entries for a logger. My post was driven by the idea that it logs GET parameters but not POST. (I'm using it for logging calls to some REST API I built and my logs for POST calls are "a bit thin".)

I can't see a processor that is able add a context to all log entries, is there? Maybe this would be interesting?

**Comment by Seldaek** [comment]
Well WebProcessor adds a bit of metadata to every record, which yes I think is also overkill, but all the POST data could be potentially a lot of data, so that makes it even worse :)

You can very easily do it though..

```
$logger->pushProcessor(function ($record) {
    $record['extra']['postData'] = $_POST;
    return $record;
});
```

That's all you need to add it to every record passing through.. I don't think it warrants having 15 options in monolog as it's so easy to roll your own.
