### ISSUE TITLE
StreamHandler: closes resources it did not open

### ISSUE THREAD

**Issue by stuartherbert** [Seldaek/monolog#764]
StreamHander::close() is called when the StreamHandler is destroyed. It fclose()s the stream that StreamHandler is writing to.

However, StreamHandler doesn't actually own that stream - the stream is passed into StreamHandler by the caller. This causes problems for apps that rely on the stream to continue to exist after the StreamHandler has gone out of scope.

A good way to reproduce this is to create a StreamHandler(STDOUT) from inside a PHPUnit test. StreamHandler::close() will close STDOUT, and then PHPUnit cannot write any more output to the console.

**Comment by Seldaek** [comment]
That's a good point, I guess it should only fclose if it fopen'd it.

**Comment by xabbuh** [comment]
@Seldaek I guess it would be good to somehow document that change in the changelog because the developer now must handle closing the resource themself. Previously, they were not able to do that so updating to the next patch release will require some work.

**Comment by Seldaek** [comment]
Yup I usually update by hand before releasing otherwise I lose track of what's in it already :)

For sure this is a small BC break of sorts, but I don't think it should affect many people as php will close the resource anyway on its own in the general case (excl long-running processes). Maybe we should add a getStream() actually to let users retrieve the stream and act on it if needed.

**Comment by xabbuh** [comment]
I think what you put into the release note is good enough. :+1: Thanks for that!
