### ISSUE TITLE
ErrorHandler only logs error levels set by error_reporting

### ISSUE THREAD

**Issue by masterada** [Seldaek/monolog#815]
In ErrorHandler.php, we should be able to turn this check off:

        if (!(error_reporting() & $code)) {
            return;
        }

As this check makes it harder to replace legacy error handling with Monolog's error handler.

**Comment by masterada** [comment]
#816

**Comment by keywan-ghadami-oxid** [comment]
Hi i have the similar problem because the Monolog ErrorHandler stops on this condition it does not even call parent ErrorHandlers which makes it incompatible with other ErrorHandlers.

I did not notice that you already created a pull request please have a look at
https://github.com/keywan-ghadami-oxid/monolog/pull/1/files
Maybe we can combine them what do you think?

**Comment by xabbuh** [comment]
I guess this can be closed as it was solved by #816 and is part of Monolog 1.21.

**Comment by Seldaek** [comment]
Right sorry I missed that it was still open :)
