### ISSUE TITLE
WebProcessor does not account for HTTP_X_FORWARDED_FOR

### ISSUE THREAD

**Issue by InstanceOfMichael** [Seldaek/monolog#820]
This means that all my logs now claim that my users came from my proxy cluster and their real IP address (provided by `HTTP_X_FORWARDED_FOR`) is dropped.

This is the work-around I use inside my logging processor:
```
            $ip = env('HTTP_X_FORWARDED_FOR',env('REMOTE_ADDR',false));
            if ($ip)
            {
                $extra['ip'] = $ip;
            }
```

**Comment by Seldaek** [comment]
That is correct, but we can not blindly trust the X-Forwarded-For header as it is possible to spoof it, it must be carefully considered which IPs can be trusted (because they are your proxies that you control) and then drop these to identify the real client id. This can not be done automatically so we can't really fix this for you. The best is to write your own processor if you need this, as you did it seems. I'd look at the symfony request implementation (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L793) though because your approach is not safe and allows users to spoof their IPs.
