### ISSUE TITLE
LogstashFormatter record[level_name] is is mapped to message[level], record[level] is not mapped at all

### ISSUE THREAD

**Issue by pupsschluepfer** [Seldaek/monolog#913]
Shouldn't a mapping from monolog-record to logstash-message be as accurate as possible?

```php
// ...
if (isset($record['level_name'])) {
    $message['level_name'] = $record['level_name'];
}
if (isset($record['level'])) {
    $message['level'] = $record['level'];
}
// ...
```

At the moment the content of `$record['level_name']` is just written to `$message['level']`. IMHO this might be a little misleading because most loggin-systems consider `level` an interger and `level_name` a human-readable string.

**Comment by Seldaek** [comment]
This was done when logstash V1 was added, before we used the level alone for V0.. I guess the problem is that while a lot of systems treat levels as integers, the exact numbers used vary. Names are at least non ambiguous. And well changing this at this point would break things for existing users that built tooling around these messages, so not sure it's worth it..

**Comment by pupsschluepfer** [comment]
Concerning existing solutions, you're right of course.
Maybe it would be an option to just map the (int)$record[level] to some extra field in $message so that this value is at least present in the message, too.

**Comment by Seldaek** [comment]
Sure that'd be an option.

**Comment by pupsschluepfer** [comment]
How can I add a pull-request?

**Comment by Seldaek** [comment]
https://help.github.com/articles/creating-a-pull-request/
