### ISSUE TITLE
SlackWebhookHandler can't prevent RuntimeException [proposal]

### ISSUE THREAD

**Issue by vrubiella** [Seldaek/monolog#920]
If slack sevice is down (or inactivated webhook), slow, or url is malformed, a Fatal RuntimeException raised.

I propose add configure options on the handler to ignore this errors or define timeout requests.

In other case we are "hard-coupling" our service to slack service.

**Comment by an1zhegorodov** [comment]
@vrubiella Have you tried WhatFailureGroupHandler?

**Comment by Seldaek** [comment]
We offer the WhatFailureGroupHandler that lets you ignore failures from any handler. It's the recommended way to go because it lets you configure everything without hiding errors, and once you know everything work, if you think the logging is non-essential then you can wrap it with that and make sure a log failure does not bring down the application with it.

**Comment by vrubiella** [comment]
@Seldaek I didn't read you. Thanks!
