### ISSUE TITLE
how can i add extra data to records?

### ISSUE THREAD

**Issue by hebaoxia** [Seldaek/monolog#988]
because i don't like to modify too much code. such as add a $extra parameter to every Logger method. so i add two methods as below and it's work well.

file:src/Monolog/Logger.php
```
    /**
     * Set the extra information of log records
     *
     * @param array $extra
     *
     * @return $this
     */
    public function setExtra(array $extra = [])
    {
        self::$extra = $extra;

        return $this;
    }

    /**
     * Get the extra information
     *
     * @return array
     */
    public function getExtra()
    {
        $extra = self::$extra;
        // reset extra information
        $this->setExtra([]);

        return $extra;
    }
```

then replace "'extra' => array()," with "'extra' => $this->getExtra(),".

i use it like this:
```
    getLogger('app')->setExtra([my extra information array])->debug($message, $content);
```

i know it is ugly but it's work. do you have some other ways?

**Comment by stof** [comment]
there are 2 ways ways to enrich the record, depending on where you have this info:

- if you want to add the info for a particular record from the place where you log things, PSR-3 has you covered thanks to the `$context` argument of all logging methods of the interface (the one you filled with a variable named `$content` in your code snippet above, which looks weird)
- if you want to add some info added in every record, you should register a processor in the Monolog Logger, which is a callable responsible for altering the record before actually logging it (and the convention is to put he extra infos in `$record['extra']`, otherwise it may get ignored by handlers)

As your use case above seems to be related to adding some info from the logging location (as you add one-time extras), you should use the context.

**Comment by hebaoxia** [comment]
thank you @stof
